RiskManagementModels:
  - name: RiskManagement1
    type: Model
  - name: RiskManagement2
    type: Manual

TradingModels:
  - name: Strategy1
    type: Model
    source: PyTorch
  - name: Strategy2
    type: Model
    source: PyTorch

PortfolioManagementModel:
  type: Manual
  take_profit: 0.02
  stop_loss: 0.02